logging:
    level:
        root: OFF
        com.example.webServlet: INFO
        org.springframework.spring-web: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file:
        name: logs/myapp.log

springdoc:
    apiDocs:
        path: /api-docs