spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_schema
    username: my_username
    password: my_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: OFF
    com.hillel: INFO
    org.springframework.spring-web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: logs/myapp.log
